### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by JacMeOuf** [Ximaz/megaloader#15]
I see the python code you have written. just pointing out your 'requirements.txt' has spelt 'colorama' as 'coloram'.
I have an issue:
I can't install the required dependencies. It always says, 'import failed'. May i know what i could do? I will just look through the code while waiting for reply. Thanks.

Error message:
webdriver-manager>=3.8.3 module not found, CulturedDownloader will install it for you...
webdriver-manager>=3.8.3 module has been installed.

Cultured Downloader is missing some files, downloading 4.2.1...
Download completed...
Failed to import Cultured Downloader.
Please try again, orcheck for a newer launcher on Cultured Downloader's GitHub Repository.
You may also raise an issue on Cultured Downloader's GitHub Repository if you are unable to resolve this issue.
Press ENTER to exit...

**Comment by Ximaz** [comment]
I think this issue is addressed to the wrong repository. I never used colorama as dependency for this project neither selenium or any kind of webdriver.
