### ISSUE TITLE
Some Plugins dont work anymore

### ISSUE THREAD

**Issue by Simoneeeeeeee** [Ximaz/megaloader#17]
I just tried everything because i wanted to make a GUI for the Megaloader and then Commit it to this project but it seems that Bunkr abd Rule34 doesnt really work and  Cyberdrop & Fapello seems to get a connection error after a certain time and also pls add the other plugins also to the examples. If you want we can write via Discord: Simone#0782

**Comment by Ximaz** [comment]
I would prefer you to write the code you're using when doing your tests (not the GUI one, but the actual call to the API), so I can tyr to figure out the issue. If you have a console error, please, provide it too.

**Comment by Simoneeeeeeee** [comment]
**Cyberdrop doesnt work anymore the site has some own issues so not your fault.
On Fapello you only get a connection lost error when the Profile has so many pictures/videos** 

**Bunkr Changed the Domain from bunkr.is -> bunkr.su**
code:
`def main():`
    `output = "downloads"`
    `url = "https://bunkr.su/d/megaloader-main-RKEICuly.zip"`
    `api = Bunkr(url)`
    `for u in api.export():`
        `api.download_file(u, output)`

Error:
`Traceback (most recent call last):`
  `File "c:\Users\simon.DESKTOP-D56H90E\Desktop\megaloader-main\test.py", line 14, in <module>`
    `main()`
  `File "c:\Users\simon.DESKTOP-D56H90E\Desktop\megaloader-main\test.py", line 10, in main`
    `for u in api.export():`
  `File "c:\Users\simon.DESKTOP-D56H90E\Desktop\megaloader-main\plugins\bunkr.py", line 26, in export`    
    `buildId = self.getBuildId(response.text)`
              `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "c:\Users\simon.DESKTOP-D56H90E\Desktop\megaloader-main\plugins\bunkr.py", line 17, in getBuildId`
    `return json.loads(re.search(REGEX_BUILD_ID, resText)[1])["buildId"]`
                      `~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^`
`TypeError: 'NoneType' object is not subscriptable`


**Rule34:**
Code:
`def main():`
    `output = "downloads"`
    `tags = ["bra"]`
    `api = Rule34(tags)`
    `for u in api.export():`
        `api.download_file(u, output)`

Error:
`Traceback (most recent call last):`
  `File "c:\Users\simon.DESKTOP-D56H90E\Desktop\megaloader-main\test.py", line 11, in <module>`
   `main()`
  `File "c:\Users\simon.DESKTOP-D56H90E\Desktop\megaloader-main\test.py", line 7, in main`
    `for u in api.export():`
  `File "c:\Users\simon.DESKTOP-D56H90E\Desktop\megaloader-main\plugins\rule34.py", line 23, in export`
    `data = XML_ET.fromstringlist([data])`
           `^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
  `File "C:\Users\simon.DESKTOP-D56H90E\AppData\Local\Programs\Python\Python311\Lib\xml\etree\ElementTree.py", line 1378, in fromstringlist`
    `parser.feed(text)`
`xml.etree.ElementTree.ParseError: undefined entity &nbsp;: line 11, column 3`

**Comment by Ximaz** [comment]
Thanks for providing errors, I'll find a work around.

**Comment by Ximaz** [comment]
I fixed the BUnkr plugin but unfortunately I can't do much about Rule34 since they decided to add a Captca from CLoudflare to their services, so I can't reach the XML I needed to get parse.
