### ISSUE TITLE
How to download specific folders from a gofile link

### ISSUE THREAD

**Issue by kerendanan1511** [Ximaz/megaloader#20]
Hi, 

I have a url to a gofile directory but the folders I want to download don't have a path to download.. I think this is how gofile works, by clicking to recursive folders you still get the same path url of the root directory. 
Any idea how I can specify in the code to select folders to download? 

Thanks :)

**Comment by Ximaz** [comment]
Hi, can you provide the URL you're trying to download from ?

**Comment by kerendanan1511** [comment]
Unfortunetaly this is a private data due to clinical research. 
Here is a screenshot representing my issue:
<img width="827" alt="Screenshot 2023-04-03 at 13 25 40" src="https://user-images.githubusercontent.com/59691157/229484355-2fc5fc9e-5979-46e1-b5d5-8e8766449ddf.png">

I want the download the files in root/F19FTSEUET0193/CleanData and only have the link to F19FTSEUET0193_unstimulated. 

Hope this is still useful for my problem :)

**Comment by Alibragi** [comment]
It works for me when the url is in the classic format:

`https://gofile.io/d/XXXXX`

How's your gofile url like?

**Comment by Ximaz** [comment]
Yes it's because the script is made for this URL. Is there another URL I have to handler ?

**Comment by Cestvia** [comment]
I'm sorry I'm not a dev, can you guide me step by step to be able to run your project for download? I installed python 3.9 and i don't know what is the next step.

**Comment by Ximaz** [comment]
> I'm sorry I'm not a dev, can you guide me step by step to be able to run your project for download? I installed python 3.9 and i don't know what is the next step.

Open a new issue for that please.
