### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by Cestvia** [Ximaz/megaloader#21]
Can you guide me step by step to be able to run your project for download? I installed python 3.9, cloned this project in my computer. I read through a few issues solved and followed, suppose i want to download a file from gofile, i copied file gofile.py and replace url in it from examples folder to megaloader folder, next step i have to what to do to run it?

**Comment by Alibragi** [comment]
Open windows prompt (one way is WIN+R, type "cmd", hit ENTER)

cd to your megaloader directory (eg: C:\megaloader), the one containing the gofile.py you wrote about

From there type "python gofile.py" followed by enter to execute that.

C:\megaloader\> python gofile.py [ENTER]

**Comment by Cestvia** [comment]
![image](https://user-images.githubusercontent.com/131637453/233959254-ea1b5840-1e73-4d24-9f5d-9a1eda1dc380.png)
I tried copy gofile.py file and paste in test.py file, everything seems to work, no error message but i cant find where downloaded file, how do i configure the address download of the file

**Comment by Alibragi** [comment]
gofile.py has a line output = "downloads", that's the name of the folder it saves the files
You have to create manually this folder under "d:\megaloader-main"
to have "d:\megaloader-main\downloads"

**Comment by Cestvia** [comment]
Thank you very much, last question: What is the limitation of this project? Can only download photos? Can I download zip files? What is the capacity limit?

**Comment by Alibragi** [comment]
I'm not python expert but I think it has no limitations.
I'm downloading photos and videos no problems.

**Comment by Cestvia** [comment]
Thank you.
