### ISSUE TITLE
Problem with download with Gofile

### ISSUE THREAD

**Issue by RavenIs57** [Ximaz/megaloader#22]
Hello,
 I am having problems using the test.py script with the download configuration for Gofile, I ran the file in Debug mode and it gave me this error
![Screenshot_2](https://github.com/Ximaz/megaloader/assets/135260312/65c83d4f-aaad-4710-9323-7ad70842c284)

Then, I did the same with the Init file, and it gave me this error
![Screenshot_3](https://github.com/Ximaz/megaloader/assets/135260312/a3fa15b7-c5bc-48be-aca1-f56c00de6c14)

What could be the problem? I reinstalled the program, reinstalled the requirements from the file requirements.txt and the problem continues

Thanks !

**Comment by Ximaz** [comment]
Hi, don't change the source code. You passed ˋuˋ to the download function but it's ˋurlˋ.

**Comment by RavenIs57** [comment]
I'm sorry but in which line was the change ? Because the only thing I have edited was the download url and the directory. I compared the file on github with mine and I can't find the difference. Thanks for answer.

**Comment by Ximaz** [comment]
9th line in test.py

**Comment by RavenIs57** [comment]
ok, i made the change but now i have this Issue, i ran the script but it takes about 5 seconds and then it's like it finished downloading, but in the directory it doesn't show any files coming from GoFile, it doesn't throw any error in the terminal. I verified that the url was correct
![image](https://github.com/Ximaz/megaloader/assets/135260312/463efc7b-4b38-4b2c-8699-729cea5a91ba)

**Comment by Ximaz** [comment]
Hello again,
I needed to update the script for GoFile because apparently, a constant changed. You can now pull the changes and run this script :

```python
from plugins import GoFile


def main():
    output = "downloads"
    url = "https://gofile.io/d/GZDV36"
    api = GoFile(url)
    for u in api.export():
        print(u)
        api.download_file(u, output)

if __name__ == "__main__":
    main()
```
And make sure the ``downloads`` folder exists before running the script.
