### ISSUE TITLE
GoFile snippet error

### ISSUE THREAD

**Issue by jankintu** [Ximaz/megaloader#5]
Hi, great repo by the way

I want to ask you about this error since i already pulled up-to-date version from this repo and tried GoFIle snippet

```
Traceback (most recent call last):
  File "gofile.py", line 1, in <module>
    from plugins import GoFile
  File "/home/user/repo/megaloader/plugins/__init__.py", line 1, in <module>
    from .pixiv import Pixiv
  File "/home/user/repo/megaloader/plugins/pixiv.py", line 6
    def __init__(self, creator_id: str, PHPSESSID: str = None):
                                 ^
SyntaxError: invalid syntax
```

Thanks

**Comment by Ximaz** [comment]
Hi, thanks for the report, I'm going to check this ASAP and let you know about this error.
It shouldn't take too long, stay tuned.

**Comment by Ximaz** [comment]
Ok, I think you're running the script with Python 2.X, where the following syntax is not available :
```python
def doing_something(a: str) -> bool:
    print(a)
    return True
```
Because the typing were added for Python 3.X. I suggest you to re-run the script using Python 3.
