### ISSUE TITLE
issue when running 

### ISSUE THREAD

**Issue by MehrabD123** [Ximaz/megaloader#6]
Traceback (most recent call last):
  File "C:\Users\__\Desktop\megaloader-main1\test.py", line 13, in <module>
    main()
  File "C:\Users\__\Desktop\megaloader-main1\test.py", line 9, in main
    for u in api.fetch_resources(url, password):
  File "C:\Users\__\Desktop\megaloader-main1\plugins\gofile.py", line 38, in fetch_resources
    raise GoFileErrorPageNotFound()
plugins.gofile.GoFileErrorPageNotFound

i keep getting this issue when attempting to run the gofile plugin, any idea as to what the issue is?

**Comment by Ximaz** [comment]
Hi, thanks for opening this issue.
Can I see the main function from ``test.py`` ? I would see the params you supplied to the GoFile plugin.
Thanks in advance.

**Comment by MehrabD123** [comment]
this is the test.py file
from plugins import GoFile

def main():
    output = "downloads"
    url = "link"
    password = "None"

    api = GoFile()
    for u in api.fetch_resources(url, password):
        api.download_file(u, output)

if __name__ == "__main__":
    main()

**Comment by Ximaz** [comment]
Alright, did you changed the ``link`` by the actual GoFile URL you want to download ?

**Comment by MehrabD123** [comment]
yeah i just replaced the actual one with the word link, but when i run it the link is there

**Comment by Ximaz** [comment]
Can you send me the link ?

**Comment by MehrabD123** [comment]
https://gofile.io/d/tcjOzx
this is the link

**Comment by Ximaz** [comment]
The link you're trying to download archives from has been taken down or is wrong spelled :
<img width="582" alt="gofile" src="https://user-images.githubusercontent.com/64309998/163734876-2b8f9450-08f9-469f-98f3-5e213f6f1abf.png">

**Comment by MehrabD123** [comment]
i am able to access the link just fine, but even with other links it still doesnt work, i just tested out the cyberdrop plugin and that worked fine, my issue seems to only lie with the gofile plugin
![image](https://user-images.githubusercontent.com/66188122/163734952-2ee249c3-d363-4092-8a9e-d0f5a5db18e3.png)

**Comment by Ximaz** [comment]
Well, it seems you didn't copy the same link because even without using the plugin, I'm not able to reach the folder. Or, maybe the link you're trying to a access in one stored on your private personal profile, which the plugin isn't able to access.

**Comment by MehrabD123** [comment]
can you access this test file i uploaded?

**Comment by Ximaz** [comment]
Yes, I'am able to access to this file.

**Comment by MehrabD123** [comment]
when i use this test file int he gofile plugin i still receive this error
![image](https://user-images.githubusercontent.com/66188122/163735143-770a1e03-54e8-42c0-af55-7e27ef3563c2.png)

**Comment by Ximaz** [comment]
I'm going to investigate.

**Comment by Ximaz** [comment]
Alright, so, I just printed out the data the script received from the server and it seems like the script has been patched. I'm going to find a workaround to this issue, but for now it seems the route I was using to download is now usable only by premium users.
<img width="582" alt="Capture d’écran 2022-04-18 à 00 58 36" src="https://user-images.githubusercontent.com/64309998/163735299-2a2e5aad-2adf-42cd-810b-ccb122390a17.png">

**Comment by Ximaz** [comment]
Alright, it's fixed. You can now fetch the megaloader's update and go back to your downloads.
